#!/usr/bin/env php
<?php

require(__DIR__ . '/functions.php');

//для консольного app - оставляю все в режиме DEBUG.
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');
require(__DIR__ . '/common/config/bootstrap.php');
require(__DIR__ . '/console/config/bootstrap.php');

try {
    $application = new yii\console\Application(require(__DIR__ . '/config/console/config.php'));
    $exitCode = $application->run();
    exit($exitCode);
} catch (\yii\base\InvalidConfigException $e) {
}
